# Generated by Django 2.1.2 on 2019-06-05 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190530_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 5, 11, 27, 51, 140937, tzinfo=utc)),
        ),
    ]
