# Generated by Django 2.1.2 on 2019-05-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sku', models.CharField(default='2R5Fms0RF0kYAxc5A8pnNQ', editable=False, max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
