# Generated by Django 2.1.4 on 2019-05-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sku',
            field=models.CharField(default='9c7cXma8YbJw44CQj0He1g', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
    ]
