# Generated by Django 2.1.2 on 2019-05-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sku',
            field=models.CharField(default='Yk5ksfc5aFmUFTyBZodojg', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
    ]
