# Generated by Django 2.1.2 on 2019-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190528_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sku',
            field=models.CharField(default='owdObA90E9uFUeUSOdvTBQ', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
    ]
