# Generated by Django 2.1.2 on 2019-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20190530_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sku',
            field=models.CharField(default='j6t8A3GTqWFdfCc9E0qe-Q', editable=False, max_length=128, primary_key=True, serialize=False),
        ),
    ]
